[package]
name = "runzfsd"
version = "0.1.0"
authors = ["Pando85 <pando855@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
